/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as SurveyorsRouteImport } from './routes/surveyors'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MarketRouteImport } from './routes/market'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as ForeclosuresRouteImport } from './routes/foreclosures'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DiasporaRouteImport } from './routes/diaspora'
import { Route as DemoLoginRouteImport } from './routes/demo-login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContractorsRouteImport } from './routes/contractors'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as BrokersRouteImport } from './routes/brokers'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SurveyorsRegisterRouteImport } from './routes/surveyors.register'
import { Route as PropertyIdRouteImport } from './routes/property.$id'
import { Route as ListingsNewRouteImport } from './routes/listings_.new'
import { Route as ForeclosuresGuideRouteImport } from './routes/foreclosures_.guide'
import { Route as ForeclosuresIdRouteImport } from './routes/foreclosures_.$id'
import { Route as ContractorsRegisterRouteImport } from './routes/contractors.register'
import { Route as BrokersRegisterRouteImport } from './routes/brokers.register'
import { Route as AgentsRegisterRouteImport } from './routes/agents.register'
import { Route as AgencyRegisterRouteImport } from './routes/agency.register'
import { Route as AgencyDashboardRouteImport } from './routes/agency.dashboard'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminRatesRouteImport } from './routes/admin.rates'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as AdminListingsRouteImport } from './routes/admin.listings'
import { Route as AdminForeclosuresRouteImport } from './routes/admin.foreclosures'
import { Route as AdminFlagsRouteImport } from './routes/admin.flags'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api.public.stripe-webhook'
import { Route as ApiPublicEstimateRouteImport } from './routes/api.public.estimate'
import { Route as ApiPublicChatRouteImport } from './routes/api.public.chat'
import { Route as ApiPublicHooksSyncHudRouteImport } from './routes/api/public/hooks/sync-hud'

const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyorsRoute = SurveyorsRouteImport.update({
  id: '/surveyors',
  path: '/surveyors',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const ForeclosuresRoute = ForeclosuresRouteImport.update({
  id: '/foreclosures',
  path: '/foreclosures',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DiasporaRoute = DiasporaRouteImport.update({
  id: '/diaspora',
  path: '/diaspora',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoLoginRoute = DemoLoginRouteImport.update({
  id: '/demo-login',
  path: '/demo-login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorsRoute = ContractorsRouteImport.update({
  id: '/contractors',
  path: '/contractors',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokersRoute = BrokersRouteImport.update({
  id: '/brokers',
  path: '/brokers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyorsRegisterRoute = SurveyorsRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => SurveyorsRoute,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsNewRoute = ListingsNewRouteImport.update({
  id: '/listings_/new',
  path: '/listings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ForeclosuresGuideRoute = ForeclosuresGuideRouteImport.update({
  id: '/foreclosures_/guide',
  path: '/foreclosures/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ForeclosuresIdRoute = ForeclosuresIdRouteImport.update({
  id: '/foreclosures_/$id',
  path: '/foreclosures/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorsRegisterRoute = ContractorsRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => ContractorsRoute,
} as any)
const BrokersRegisterRoute = BrokersRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => BrokersRoute,
} as any)
const AgentsRegisterRoute = AgentsRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AgentsRoute,
} as any)
const AgencyRegisterRoute = AgencyRegisterRouteImport.update({
  id: '/agency/register',
  path: '/agency/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyDashboardRoute = AgencyDashboardRouteImport.update({
  id: '/agency/dashboard',
  path: '/agency/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRatesRoute = AdminRatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsRoute = AdminListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminForeclosuresRoute = AdminForeclosuresRouteImport.update({
  id: '/foreclosures',
  path: '/foreclosures',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFlagsRoute = AdminFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEstimateRoute = ApiPublicEstimateRouteImport.update({
  id: '/api/public/estimate',
  path: '/api/public/estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatRoute = ApiPublicChatRouteImport.update({
  id: '/api/public/chat',
  path: '/api/public/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncHudRoute = ApiPublicHooksSyncHudRouteImport.update({
  id: '/api/public/hooks/sync-hud',
  path: '/api/public/hooks/sync-hud',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/brokers': typeof BrokersRouteWithChildren
  '/compare': typeof CompareRoute
  '/contractors': typeof ContractorsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/demo-login': typeof DemoLoginRoute
  '/diaspora': typeof DiasporaRoute
  '/favorites': typeof FavoritesRoute
  '/foreclosures': typeof ForeclosuresRoute
  '/listings': typeof ListingsRoute
  '/market': typeof MarketRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/signup': typeof SignupRoute
  '/surveyors': typeof SurveyorsRouteWithChildren
  '/transfers': typeof TransfersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/foreclosures': typeof AdminForeclosuresRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/rates': typeof AdminRatesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/users': typeof AdminUsersRoute
  '/agency/dashboard': typeof AgencyDashboardRoute
  '/agency/register': typeof AgencyRegisterRoute
  '/agents/register': typeof AgentsRegisterRoute
  '/brokers/register': typeof BrokersRegisterRoute
  '/contractors/register': typeof ContractorsRegisterRoute
  '/foreclosures/$id': typeof ForeclosuresIdRoute
  '/foreclosures/guide': typeof ForeclosuresGuideRoute
  '/listings/new': typeof ListingsNewRoute
  '/property/$id': typeof PropertyIdRoute
  '/surveyors/register': typeof SurveyorsRegisterRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/estimate': typeof ApiPublicEstimateRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/hooks/sync-hud': typeof ApiPublicHooksSyncHudRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/brokers': typeof BrokersRouteWithChildren
  '/compare': typeof CompareRoute
  '/contractors': typeof ContractorsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/demo-login': typeof DemoLoginRoute
  '/diaspora': typeof DiasporaRoute
  '/favorites': typeof FavoritesRoute
  '/foreclosures': typeof ForeclosuresRoute
  '/listings': typeof ListingsRoute
  '/market': typeof MarketRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/signup': typeof SignupRoute
  '/surveyors': typeof SurveyorsRouteWithChildren
  '/transfers': typeof TransfersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/foreclosures': typeof AdminForeclosuresRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/rates': typeof AdminRatesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/users': typeof AdminUsersRoute
  '/agency/dashboard': typeof AgencyDashboardRoute
  '/agency/register': typeof AgencyRegisterRoute
  '/agents/register': typeof AgentsRegisterRoute
  '/brokers/register': typeof BrokersRegisterRoute
  '/contractors/register': typeof ContractorsRegisterRoute
  '/foreclosures/$id': typeof ForeclosuresIdRoute
  '/foreclosures/guide': typeof ForeclosuresGuideRoute
  '/listings/new': typeof ListingsNewRoute
  '/property/$id': typeof PropertyIdRoute
  '/surveyors/register': typeof SurveyorsRegisterRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/estimate': typeof ApiPublicEstimateRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/hooks/sync-hud': typeof ApiPublicHooksSyncHudRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/brokers': typeof BrokersRouteWithChildren
  '/compare': typeof CompareRoute
  '/contractors': typeof ContractorsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/demo-login': typeof DemoLoginRoute
  '/diaspora': typeof DiasporaRoute
  '/favorites': typeof FavoritesRoute
  '/foreclosures': typeof ForeclosuresRoute
  '/listings': typeof ListingsRoute
  '/market': typeof MarketRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/signup': typeof SignupRoute
  '/surveyors': typeof SurveyorsRouteWithChildren
  '/transfers': typeof TransfersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/foreclosures': typeof AdminForeclosuresRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/rates': typeof AdminRatesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/users': typeof AdminUsersRoute
  '/agency/dashboard': typeof AgencyDashboardRoute
  '/agency/register': typeof AgencyRegisterRoute
  '/agents/register': typeof AgentsRegisterRoute
  '/brokers/register': typeof BrokersRegisterRoute
  '/contractors/register': typeof ContractorsRegisterRoute
  '/foreclosures_/$id': typeof ForeclosuresIdRoute
  '/foreclosures_/guide': typeof ForeclosuresGuideRoute
  '/listings_/new': typeof ListingsNewRoute
  '/property/$id': typeof PropertyIdRoute
  '/surveyors/register': typeof SurveyorsRegisterRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/estimate': typeof ApiPublicEstimateRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/hooks/sync-hud': typeof ApiPublicHooksSyncHudRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agents'
    | '/alerts'
    | '/auth'
    | '/brokers'
    | '/compare'
    | '/contractors'
    | '/dashboard'
    | '/demo-login'
    | '/diaspora'
    | '/favorites'
    | '/foreclosures'
    | '/listings'
    | '/market'
    | '/messages'
    | '/profile'
    | '/safety'
    | '/signup'
    | '/surveyors'
    | '/transfers'
    | '/admin/analytics'
    | '/admin/flags'
    | '/admin/foreclosures'
    | '/admin/listings'
    | '/admin/partners'
    | '/admin/rates'
    | '/admin/security'
    | '/admin/users'
    | '/agency/dashboard'
    | '/agency/register'
    | '/agents/register'
    | '/brokers/register'
    | '/contractors/register'
    | '/foreclosures/$id'
    | '/foreclosures/guide'
    | '/listings/new'
    | '/property/$id'
    | '/surveyors/register'
    | '/api/public/chat'
    | '/api/public/estimate'
    | '/api/public/stripe-webhook'
    | '/api/public/hooks/sync-hud'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agents'
    | '/alerts'
    | '/auth'
    | '/brokers'
    | '/compare'
    | '/contractors'
    | '/dashboard'
    | '/demo-login'
    | '/diaspora'
    | '/favorites'
    | '/foreclosures'
    | '/listings'
    | '/market'
    | '/messages'
    | '/profile'
    | '/safety'
    | '/signup'
    | '/surveyors'
    | '/transfers'
    | '/admin/analytics'
    | '/admin/flags'
    | '/admin/foreclosures'
    | '/admin/listings'
    | '/admin/partners'
    | '/admin/rates'
    | '/admin/security'
    | '/admin/users'
    | '/agency/dashboard'
    | '/agency/register'
    | '/agents/register'
    | '/brokers/register'
    | '/contractors/register'
    | '/foreclosures/$id'
    | '/foreclosures/guide'
    | '/listings/new'
    | '/property/$id'
    | '/surveyors/register'
    | '/api/public/chat'
    | '/api/public/estimate'
    | '/api/public/stripe-webhook'
    | '/api/public/hooks/sync-hud'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agents'
    | '/alerts'
    | '/auth'
    | '/brokers'
    | '/compare'
    | '/contractors'
    | '/dashboard'
    | '/demo-login'
    | '/diaspora'
    | '/favorites'
    | '/foreclosures'
    | '/listings'
    | '/market'
    | '/messages'
    | '/profile'
    | '/safety'
    | '/signup'
    | '/surveyors'
    | '/transfers'
    | '/admin/analytics'
    | '/admin/flags'
    | '/admin/foreclosures'
    | '/admin/listings'
    | '/admin/partners'
    | '/admin/rates'
    | '/admin/security'
    | '/admin/users'
    | '/agency/dashboard'
    | '/agency/register'
    | '/agents/register'
    | '/brokers/register'
    | '/contractors/register'
    | '/foreclosures_/$id'
    | '/foreclosures_/guide'
    | '/listings_/new'
    | '/property/$id'
    | '/surveyors/register'
    | '/api/public/chat'
    | '/api/public/estimate'
    | '/api/public/stripe-webhook'
    | '/api/public/hooks/sync-hud'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgentsRoute: typeof AgentsRouteWithChildren
  AlertsRoute: typeof AlertsRoute
  AuthRoute: typeof AuthRoute
  BrokersRoute: typeof BrokersRouteWithChildren
  CompareRoute: typeof CompareRoute
  ContractorsRoute: typeof ContractorsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DemoLoginRoute: typeof DemoLoginRoute
  DiasporaRoute: typeof DiasporaRoute
  FavoritesRoute: typeof FavoritesRoute
  ForeclosuresRoute: typeof ForeclosuresRoute
  ListingsRoute: typeof ListingsRoute
  MarketRoute: typeof MarketRoute
  MessagesRoute: typeof MessagesRoute
  ProfileRoute: typeof ProfileRoute
  SafetyRoute: typeof SafetyRoute
  SignupRoute: typeof SignupRoute
  SurveyorsRoute: typeof SurveyorsRouteWithChildren
  TransfersRoute: typeof TransfersRoute
  AgencyDashboardRoute: typeof AgencyDashboardRoute
  AgencyRegisterRoute: typeof AgencyRegisterRoute
  ForeclosuresIdRoute: typeof ForeclosuresIdRoute
  ForeclosuresGuideRoute: typeof ForeclosuresGuideRoute
  ListingsNewRoute: typeof ListingsNewRoute
  PropertyIdRoute: typeof PropertyIdRoute
  ApiPublicChatRoute: typeof ApiPublicChatRoute
  ApiPublicEstimateRoute: typeof ApiPublicEstimateRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicHooksSyncHudRoute: typeof ApiPublicHooksSyncHudRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveyors': {
      id: '/surveyors'
      path: '/surveyors'
      fullPath: '/surveyors'
      preLoaderRoute: typeof SurveyorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foreclosures': {
      id: '/foreclosures'
      path: '/foreclosures'
      fullPath: '/foreclosures'
      preLoaderRoute: typeof ForeclosuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diaspora': {
      id: '/diaspora'
      path: '/diaspora'
      fullPath: '/diaspora'
      preLoaderRoute: typeof DiasporaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-login': {
      id: '/demo-login'
      path: '/demo-login'
      fullPath: '/demo-login'
      preLoaderRoute: typeof DemoLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractors': {
      id: '/contractors'
      path: '/contractors'
      fullPath: '/contractors'
      preLoaderRoute: typeof ContractorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brokers': {
      id: '/brokers'
      path: '/brokers'
      fullPath: '/brokers'
      preLoaderRoute: typeof BrokersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveyors/register': {
      id: '/surveyors/register'
      path: '/register'
      fullPath: '/surveyors/register'
      preLoaderRoute: typeof SurveyorsRegisterRouteImport
      parentRoute: typeof SurveyorsRoute
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings_/new': {
      id: '/listings_/new'
      path: '/listings/new'
      fullPath: '/listings/new'
      preLoaderRoute: typeof ListingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foreclosures_/guide': {
      id: '/foreclosures_/guide'
      path: '/foreclosures/guide'
      fullPath: '/foreclosures/guide'
      preLoaderRoute: typeof ForeclosuresGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foreclosures_/$id': {
      id: '/foreclosures_/$id'
      path: '/foreclosures/$id'
      fullPath: '/foreclosures/$id'
      preLoaderRoute: typeof ForeclosuresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractors/register': {
      id: '/contractors/register'
      path: '/register'
      fullPath: '/contractors/register'
      preLoaderRoute: typeof ContractorsRegisterRouteImport
      parentRoute: typeof ContractorsRoute
    }
    '/brokers/register': {
      id: '/brokers/register'
      path: '/register'
      fullPath: '/brokers/register'
      preLoaderRoute: typeof BrokersRegisterRouteImport
      parentRoute: typeof BrokersRoute
    }
    '/agents/register': {
      id: '/agents/register'
      path: '/register'
      fullPath: '/agents/register'
      preLoaderRoute: typeof AgentsRegisterRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agency/register': {
      id: '/agency/register'
      path: '/agency/register'
      fullPath: '/agency/register'
      preLoaderRoute: typeof AgencyRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency/dashboard': {
      id: '/agency/dashboard'
      path: '/agency/dashboard'
      fullPath: '/agency/dashboard'
      preLoaderRoute: typeof AgencyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rates': {
      id: '/admin/rates'
      path: '/rates'
      fullPath: '/admin/rates'
      preLoaderRoute: typeof AdminRatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings': {
      id: '/admin/listings'
      path: '/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminListingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/foreclosures': {
      id: '/admin/foreclosures'
      path: '/foreclosures'
      fullPath: '/admin/foreclosures'
      preLoaderRoute: typeof AdminForeclosuresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/flags': {
      id: '/admin/flags'
      path: '/flags'
      fullPath: '/admin/flags'
      preLoaderRoute: typeof AdminFlagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/estimate': {
      id: '/api/public/estimate'
      path: '/api/public/estimate'
      fullPath: '/api/public/estimate'
      preLoaderRoute: typeof ApiPublicEstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat': {
      id: '/api/public/chat'
      path: '/api/public/chat'
      fullPath: '/api/public/chat'
      preLoaderRoute: typeof ApiPublicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-hud': {
      id: '/api/public/hooks/sync-hud'
      path: '/api/public/hooks/sync-hud'
      fullPath: '/api/public/hooks/sync-hud'
      preLoaderRoute: typeof ApiPublicHooksSyncHudRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminFlagsRoute: typeof AdminFlagsRoute
  AdminForeclosuresRoute: typeof AdminForeclosuresRoute
  AdminListingsRoute: typeof AdminListingsRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminRatesRoute: typeof AdminRatesRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminFlagsRoute: AdminFlagsRoute,
  AdminForeclosuresRoute: AdminForeclosuresRoute,
  AdminListingsRoute: AdminListingsRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminRatesRoute: AdminRatesRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AgentsRouteChildren {
  AgentsRegisterRoute: typeof AgentsRegisterRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsRegisterRoute: AgentsRegisterRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface BrokersRouteChildren {
  BrokersRegisterRoute: typeof BrokersRegisterRoute
}

const BrokersRouteChildren: BrokersRouteChildren = {
  BrokersRegisterRoute: BrokersRegisterRoute,
}

const BrokersRouteWithChildren =
  BrokersRoute._addFileChildren(BrokersRouteChildren)

interface ContractorsRouteChildren {
  ContractorsRegisterRoute: typeof ContractorsRegisterRoute
}

const ContractorsRouteChildren: ContractorsRouteChildren = {
  ContractorsRegisterRoute: ContractorsRegisterRoute,
}

const ContractorsRouteWithChildren = ContractorsRoute._addFileChildren(
  ContractorsRouteChildren,
)

interface SurveyorsRouteChildren {
  SurveyorsRegisterRoute: typeof SurveyorsRegisterRoute
}

const SurveyorsRouteChildren: SurveyorsRouteChildren = {
  SurveyorsRegisterRoute: SurveyorsRegisterRoute,
}

const SurveyorsRouteWithChildren = SurveyorsRoute._addFileChildren(
  SurveyorsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgentsRoute: AgentsRouteWithChildren,
  AlertsRoute: AlertsRoute,
  AuthRoute: AuthRoute,
  BrokersRoute: BrokersRouteWithChildren,
  CompareRoute: CompareRoute,
  ContractorsRoute: ContractorsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DemoLoginRoute: DemoLoginRoute,
  DiasporaRoute: DiasporaRoute,
  FavoritesRoute: FavoritesRoute,
  ForeclosuresRoute: ForeclosuresRoute,
  ListingsRoute: ListingsRoute,
  MarketRoute: MarketRoute,
  MessagesRoute: MessagesRoute,
  ProfileRoute: ProfileRoute,
  SafetyRoute: SafetyRoute,
  SignupRoute: SignupRoute,
  SurveyorsRoute: SurveyorsRouteWithChildren,
  TransfersRoute: TransfersRoute,
  AgencyDashboardRoute: AgencyDashboardRoute,
  AgencyRegisterRoute: AgencyRegisterRoute,
  ForeclosuresIdRoute: ForeclosuresIdRoute,
  ForeclosuresGuideRoute: ForeclosuresGuideRoute,
  ListingsNewRoute: ListingsNewRoute,
  PropertyIdRoute: PropertyIdRoute,
  ApiPublicChatRoute: ApiPublicChatRoute,
  ApiPublicEstimateRoute: ApiPublicEstimateRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicHooksSyncHudRoute: ApiPublicHooksSyncHudRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
