/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DemoLoginRouteImport } from './routes/demo-login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContractorsRouteImport } from './routes/contractors'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as BrokersRouteImport } from './routes/brokers'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertyIdRouteImport } from './routes/property.$id'
import { Route as ListingsNewRouteImport } from './routes/listings_.new'
import { Route as AgencyRegisterRouteImport } from './routes/agency.register'
import { Route as AgencyDashboardRouteImport } from './routes/agency.dashboard'
import { Route as AdminFlagsRouteImport } from './routes/admin.flags'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api.public.stripe-webhook'
import { Route as ApiPublicEstimateRouteImport } from './routes/api.public.estimate'
import { Route as ApiPublicChatRouteImport } from './routes/api.public.chat'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoLoginRoute = DemoLoginRouteImport.update({
  id: '/demo-login',
  path: '/demo-login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorsRoute = ContractorsRouteImport.update({
  id: '/contractors',
  path: '/contractors',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokersRoute = BrokersRouteImport.update({
  id: '/brokers',
  path: '/brokers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsNewRoute = ListingsNewRouteImport.update({
  id: '/listings_/new',
  path: '/listings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyRegisterRoute = AgencyRegisterRouteImport.update({
  id: '/agency/register',
  path: '/agency/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyDashboardRoute = AgencyDashboardRouteImport.update({
  id: '/agency/dashboard',
  path: '/agency/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFlagsRoute = AdminFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEstimateRoute = ApiPublicEstimateRouteImport.update({
  id: '/api/public/estimate',
  path: '/api/public/estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatRoute = ApiPublicChatRouteImport.update({
  id: '/api/public/chat',
  path: '/api/public/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/brokers': typeof BrokersRoute
  '/compare': typeof CompareRoute
  '/contractors': typeof ContractorsRoute
  '/dashboard': typeof DashboardRoute
  '/demo-login': typeof DemoLoginRoute
  '/favorites': typeof FavoritesRoute
  '/listings': typeof ListingsRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/signup': typeof SignupRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/agency/dashboard': typeof AgencyDashboardRoute
  '/agency/register': typeof AgencyRegisterRoute
  '/listings/new': typeof ListingsNewRoute
  '/property/$id': typeof PropertyIdRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/estimate': typeof ApiPublicEstimateRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/brokers': typeof BrokersRoute
  '/compare': typeof CompareRoute
  '/contractors': typeof ContractorsRoute
  '/dashboard': typeof DashboardRoute
  '/demo-login': typeof DemoLoginRoute
  '/favorites': typeof FavoritesRoute
  '/listings': typeof ListingsRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/signup': typeof SignupRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/agency/dashboard': typeof AgencyDashboardRoute
  '/agency/register': typeof AgencyRegisterRoute
  '/listings/new': typeof ListingsNewRoute
  '/property/$id': typeof PropertyIdRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/estimate': typeof ApiPublicEstimateRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/brokers': typeof BrokersRoute
  '/compare': typeof CompareRoute
  '/contractors': typeof ContractorsRoute
  '/dashboard': typeof DashboardRoute
  '/demo-login': typeof DemoLoginRoute
  '/favorites': typeof FavoritesRoute
  '/listings': typeof ListingsRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/signup': typeof SignupRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/agency/dashboard': typeof AgencyDashboardRoute
  '/agency/register': typeof AgencyRegisterRoute
  '/listings_/new': typeof ListingsNewRoute
  '/property/$id': typeof PropertyIdRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/estimate': typeof ApiPublicEstimateRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agents'
    | '/alerts'
    | '/auth'
    | '/brokers'
    | '/compare'
    | '/contractors'
    | '/dashboard'
    | '/demo-login'
    | '/favorites'
    | '/listings'
    | '/messages'
    | '/profile'
    | '/safety'
    | '/signup'
    | '/admin/flags'
    | '/agency/dashboard'
    | '/agency/register'
    | '/listings/new'
    | '/property/$id'
    | '/api/public/chat'
    | '/api/public/estimate'
    | '/api/public/stripe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agents'
    | '/alerts'
    | '/auth'
    | '/brokers'
    | '/compare'
    | '/contractors'
    | '/dashboard'
    | '/demo-login'
    | '/favorites'
    | '/listings'
    | '/messages'
    | '/profile'
    | '/safety'
    | '/signup'
    | '/admin/flags'
    | '/agency/dashboard'
    | '/agency/register'
    | '/listings/new'
    | '/property/$id'
    | '/api/public/chat'
    | '/api/public/estimate'
    | '/api/public/stripe-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agents'
    | '/alerts'
    | '/auth'
    | '/brokers'
    | '/compare'
    | '/contractors'
    | '/dashboard'
    | '/demo-login'
    | '/favorites'
    | '/listings'
    | '/messages'
    | '/profile'
    | '/safety'
    | '/signup'
    | '/admin/flags'
    | '/agency/dashboard'
    | '/agency/register'
    | '/listings_/new'
    | '/property/$id'
    | '/api/public/chat'
    | '/api/public/estimate'
    | '/api/public/stripe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgentsRoute: typeof AgentsRoute
  AlertsRoute: typeof AlertsRoute
  AuthRoute: typeof AuthRoute
  BrokersRoute: typeof BrokersRoute
  CompareRoute: typeof CompareRoute
  ContractorsRoute: typeof ContractorsRoute
  DashboardRoute: typeof DashboardRoute
  DemoLoginRoute: typeof DemoLoginRoute
  FavoritesRoute: typeof FavoritesRoute
  ListingsRoute: typeof ListingsRoute
  MessagesRoute: typeof MessagesRoute
  ProfileRoute: typeof ProfileRoute
  SafetyRoute: typeof SafetyRoute
  SignupRoute: typeof SignupRoute
  AgencyDashboardRoute: typeof AgencyDashboardRoute
  AgencyRegisterRoute: typeof AgencyRegisterRoute
  ListingsNewRoute: typeof ListingsNewRoute
  PropertyIdRoute: typeof PropertyIdRoute
  ApiPublicChatRoute: typeof ApiPublicChatRoute
  ApiPublicEstimateRoute: typeof ApiPublicEstimateRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-login': {
      id: '/demo-login'
      path: '/demo-login'
      fullPath: '/demo-login'
      preLoaderRoute: typeof DemoLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractors': {
      id: '/contractors'
      path: '/contractors'
      fullPath: '/contractors'
      preLoaderRoute: typeof ContractorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brokers': {
      id: '/brokers'
      path: '/brokers'
      fullPath: '/brokers'
      preLoaderRoute: typeof BrokersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings_/new': {
      id: '/listings_/new'
      path: '/listings/new'
      fullPath: '/listings/new'
      preLoaderRoute: typeof ListingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency/register': {
      id: '/agency/register'
      path: '/agency/register'
      fullPath: '/agency/register'
      preLoaderRoute: typeof AgencyRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency/dashboard': {
      id: '/agency/dashboard'
      path: '/agency/dashboard'
      fullPath: '/agency/dashboard'
      preLoaderRoute: typeof AgencyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/flags': {
      id: '/admin/flags'
      path: '/flags'
      fullPath: '/admin/flags'
      preLoaderRoute: typeof AdminFlagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/estimate': {
      id: '/api/public/estimate'
      path: '/api/public/estimate'
      fullPath: '/api/public/estimate'
      preLoaderRoute: typeof ApiPublicEstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat': {
      id: '/api/public/chat'
      path: '/api/public/chat'
      fullPath: '/api/public/chat'
      preLoaderRoute: typeof ApiPublicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminFlagsRoute: typeof AdminFlagsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFlagsRoute: AdminFlagsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgentsRoute: AgentsRoute,
  AlertsRoute: AlertsRoute,
  AuthRoute: AuthRoute,
  BrokersRoute: BrokersRoute,
  CompareRoute: CompareRoute,
  ContractorsRoute: ContractorsRoute,
  DashboardRoute: DashboardRoute,
  DemoLoginRoute: DemoLoginRoute,
  FavoritesRoute: FavoritesRoute,
  ListingsRoute: ListingsRoute,
  MessagesRoute: MessagesRoute,
  ProfileRoute: ProfileRoute,
  SafetyRoute: SafetyRoute,
  SignupRoute: SignupRoute,
  AgencyDashboardRoute: AgencyDashboardRoute,
  AgencyRegisterRoute: AgencyRegisterRoute,
  ListingsNewRoute: ListingsNewRoute,
  PropertyIdRoute: PropertyIdRoute,
  ApiPublicChatRoute: ApiPublicChatRoute,
  ApiPublicEstimateRoute: ApiPublicEstimateRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
